"use client";

import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { QuickFeedbackData } from "@/types/interview";

interface QuickFeedbackProps {
  feedback: QuickFeedbackData;
  className?: string;
}

/**
 * QuickFeedback - Displays keywords, score, and summary
 * Shows immediate feedback generated by Haiku model
 */
export function QuickFeedback({ feedback, className }: QuickFeedbackProps) {
  const { keywords, score, summary } = feedback;

  // Score color mapping: 4-5 green, 3 yellow, 1-2 red
  const scoreColorClass = getScoreColorClass(score);
  const scoreLabel = getScoreLabel(score);

  return (
    <div className={cn("space-y-3", className)}>
      {/* Keywords */}
      {keywords.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          {keywords.map((keyword, index) => (
            <Badge
              key={index}
              variant="secondary"
              className="text-xs font-normal"
            >
              {keyword}
            </Badge>
          ))}
        </div>
      )}

      {/* Score + Summary */}
      <div className="flex items-center gap-3">
        <div
          className={cn(
            "flex items-center gap-1.5 rounded-md px-2 py-1",
            scoreColorClass,
          )}
        >
          <ScoreIcon score={score} />
          <span className="text-sm font-medium">{scoreLabel}</span>
        </div>
        {summary && <p className="text-sm text-muted-foreground">{summary}</p>}
      </div>
    </div>
  );
}

/**
 * Get CSS class for score color
 */
function getScoreColorClass(score: number): string {
  if (score >= 4) {
    return "bg-green-50 text-green-700 dark:bg-green-950 dark:text-green-300";
  }
  if (score === 3) {
    return "bg-yellow-50 text-yellow-700 dark:bg-yellow-950 dark:text-yellow-300";
  }
  return "bg-red-50 text-red-700 dark:bg-red-950 dark:text-red-300";
}

/**
 * Get label for score
 */
function getScoreLabel(score: number): string {
  switch (score) {
    case 5:
      return "우수";
    case 4:
      return "양호";
    case 3:
      return "보통";
    case 2:
      return "부족";
    case 1:
      return "미흡";
    default:
      return "평가됨";
  }
}

/**
 * Score icon component
 */
function ScoreIcon({ score }: { score: number }) {
  // Simple circle with number
  return (
    <span className="flex h-5 w-5 items-center justify-center rounded-full bg-current/10 text-xs font-bold">
      {score}
    </span>
  );
}

export default QuickFeedback;
