-- Migration: Create answer_feedback table for AI feedback on interview answers
-- Created: 2026-02-05
-- Issue: #1 - Archive AI Feedback

-- Create answer_feedback table
CREATE TABLE IF NOT EXISTS answer_feedback (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  answer_id uuid NOT NULL REFERENCES answers(id) ON DELETE CASCADE,

  -- Pre-generated (Haiku - immediate)
  keywords text[] DEFAULT '{}',
  quick_score integer CHECK (quick_score BETWEEN 1 AND 5),
  summary text,

  -- On-demand (Sonnet - on request)
  strengths text[] DEFAULT '{}',
  improvements text[] DEFAULT '{}',
  follow_up_questions text[] DEFAULT '{}',
  detailed_feedback text,

  -- Metadata
  pre_gen_model text DEFAULT 'haiku',
  detail_model text,
  pre_gen_tokens integer,
  detail_tokens integer,

  created_at timestamptz DEFAULT now(),
  detail_generated_at timestamptz,

  UNIQUE(answer_id)
);

-- Create index for fast lookup by answer_id
CREATE INDEX IF NOT EXISTS idx_answer_feedback_answer_id ON answer_feedback(answer_id);

-- Add comment for documentation
COMMENT ON TABLE answer_feedback IS 'Stores AI-generated feedback for interview answers including keywords, scores, and detailed analysis';
COMMENT ON COLUMN answer_feedback.keywords IS 'Array of extracted keywords from the answer (3-5 items)';
COMMENT ON COLUMN answer_feedback.quick_score IS 'Quick evaluation score (1-5) generated by Haiku model';
COMMENT ON COLUMN answer_feedback.summary IS 'One-line summary of the answer quality';
COMMENT ON COLUMN answer_feedback.strengths IS 'Array of identified strengths in the answer';
COMMENT ON COLUMN answer_feedback.improvements IS 'Array of suggested improvements';
COMMENT ON COLUMN answer_feedback.follow_up_questions IS 'Array of follow-up interview questions';
COMMENT ON COLUMN answer_feedback.detailed_feedback IS 'Comprehensive feedback text';
